//! Punycode differential vectors (generated from CPython `codecs`).
use markdown_it_rust_core::punycode::{punycode_decode, punycode_encode};

#[test]
fn punycode_matches_cpython() {
    let cases: &[(&str, &str)] = &[
        ("Üaé文文ßÜü9Z", "a9Z-skabr3e2hy567ga"),
        ("", ""),
        ("中", "fiq"),
        ("a中9", "a9-qy2c"),
        ("。éa", "a-9fa4827a"),
        ("ö9.éß中.Üü0Ü@", "9..0@-4pabu3g1f0c7682k"),
        ("éZ。Ü0", "Z0-6ha4c4088a"),
        ("-", "--"),
        ("@中üZ文-ü文Ü0", "@Z-0-ina3qc8919mj6ubca"),
        ("。@ö@", "@@-fka8829b"),
        ("中éüö文", "9ca0ar6510fdoya"),
        ("。0", "0-83t"),
        ("文.Z文", ".Z-3l7dc"),
        ("", ""),
        (".0éü中.中．0。ßé", ".0.0-yna1dd2m6726brbxcba68445c"),
        ("文é", "9ca9262c"),
        ("90@文ß．üZÜßö", "90@Z-jnaqc8pyb0794po62m"),
        ("9ü00。éaÜé.Ü-", "900a.--ssab7ic7r2966c"),
        ("ö。aéöÜ", "a-kfa2bwcc5733e"),
        ("-中ß@öa.．aÜ", "-@a.a-6paq9p8559duw7o"),
        ("-文Z文ü", "-Z-yka8604hba"),
        ("．", "5g7c"),
        ("ß", "zca"),
        ("．ö", "nda9021k"),
        ("9中中-", "9--qy2ca"),
        ("@。。Ü文文", "@-kfa3237aa0269da"),
        (".", ".-"),
        ("", ""),
        ("文文aüZ文üZ.", "aZZ.-0rab3821pad"),
        ("文", "7dv"),
        ("．中ß．", "zca3960bh56gca"),
        ("．9中", "9-lq6az377c"),
        ("Ü", "wca"),
        ("9@99。ZÜZ0.", "9@99ZZ0.-2xa2181j"),
        ("Ü文中中。ß9öé。文ü", "9-jfaj5bwdtb7331eea5160ea0786dia"),
        ("ÜZaü文ö9", "Za9-ska6k9a3621m"),
        ("．中0Zö0a", "0Z0a-6qa3179ig01l"),
        ("é。-9．ß", "-9-hia1b4947bqv8p"),
        ("-中Z", "-Z-qy2c"),
        ("Z.ZZ．öZüö", "Z.ZZZ-muab1c94292b"),
        ("ü", "tda"),
        ("文0Ü文Zü9.é中", "0Z9.-gna5f9f9689d85ubca"),
        (".文é0ß-。.üa", ".0-.a-mqa2e4hp744bp35e"),
        ("Üü中éß@ü", "@-jfaj3b3fd7349k"),
        ("@-ö", "@--gka"),
        ("-a-ÜßéÜ", "-a--vkaar4e"),
        ("ß", "zca"),
        ("-中.中", "-.-qy2cb"),
        ("é．éZü9éZa.", "Z9Za.-9raac3or031x"),
        ("ßéö。9aÜüßZ@ß", "9aZ@-hnapdc7f9fxcu016f"),
        ("ßZ-@Z@", "Z-@Z@-kqa"),
        ("文Ü@", "@-jfa6248e"),
        ("9ß文öö9aö.9文é", "99a.9-lqa8e1eac4034zha"),
        ("Ü0", "0-jfa"),
        ("", ""),
        ("文中。@-文文", "@--q13az65k8nyeaa"),
        ("", ""),
        ("中0.éüé@0.a", "0.@0.a-cvaa4o5710f"),
        ("é", "9ca"),
        ("éZ", "Z-9fa"),
        ("Bücher", "Bcher-kva"),
        ("bücher", "bcher-kva"),
        ("exämple", "exmple-cua"),
        ("MÜNCHEN", "MNCHEN-psa"),
        ("öbb.at", "bb.at-iua"),
        ("日本語", "wgv71a119e"),
        ("faß.de", "fa.de-mqa"),
        ("UPPER", "UPPER-"),
        ("ü", "tda"),
        ("", ""),
        ("a", "a-"),
        ("aB1", "aB1-"),
    ];
    for (input, expected) in cases {
        assert_eq!(&punycode_encode(input), expected, "encode {input:?}");
        if !expected.starts_with("ERROR") {
            let back = punycode_decode(expected).expect("decode");
            assert_eq!(&back.to_lowercase(), &input.to_lowercase(), "roundtrip {expected:?}");
        }
    }
}
